# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything_Golden', '0002_auto_20170212_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
