# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything_Golden', '0008_user_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(related_name='User_Orders', to='Everything_Golden.User'),
        ),
    ]
