# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything_Golden', '0009_auto_20170212_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(related_name='Event_Attendees', to='Everything_Golden.User'),
        ),
    ]
