# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything_Golden', '0012_auto_20170213_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
